{
	"version": 1714249880,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/background_spr-sheet0.png",
		"images/player_spr-sheet0.png",
		"images/enemy_spr-sheet0.png",
		"images/bullet_spr-sheet0.png",
		"images/explosion_spr-sheet0.png",
		"images/explosion2_spr-sheet0.png",
		"images/ground_1.png",
		"images/ground_2.png",
		"images/tiledbackground.png",
		"images/bullet_2-sheet0.png",
		"images/player_death_spr-sheet0.png",
		"images/explosion2_spr2-sheet0.png",
		"images/game_background_spr-sheet0.png",
		"media/music_background.m4a",
		"media/music_background.ogg",
		"media/power_up_sound.m4a",
		"media/power_up_sound.ogg",
		"media/player hurt.ogg",
		"media/shoot.ogg",
		"media/zombie attack.ogg",
		"media/zombie bgm.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}